image: Visual Studio 2017
init:
  - git config --global core.autocrlf input
install:
  - cinst fake -pre

build_script:
  - cmd: fake.exe build target NuGet

test: off

artifacts:
  - path: 'bin\*.nupkg'
    type: NuGetPackage
