// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyProductAttribute("FSharp.Formatting")>]
[<assembly: AssemblyDescriptionAttribute("A package of libraries for building great F# documentation, samples and blogs")>]
[<assembly: AssemblyVersionAttribute("6.0.1")>]
[<assembly: AssemblyFileVersionAttribute("6.0.1")>]
[<assembly: AssemblyInformationalVersionAttribute("6.0.1")>]
[<assembly: AssemblyCopyrightAttribute("Apache 2.0 License")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyProduct = "FSharp.Formatting"
    let [<Literal>] AssemblyDescription = "A package of libraries for building great F# documentation, samples and blogs"
    let [<Literal>] AssemblyVersion = "6.0.1"
    let [<Literal>] AssemblyFileVersion = "6.0.1"
    let [<Literal>] AssemblyInformationalVersion = "6.0.1"
    let [<Literal>] AssemblyCopyright = "Apache 2.0 License"
