// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProduct("FSharp.Formatting")]
[assembly: AssemblyDescription("A package of libraries for building great F# documentation, samples and blogs")]
[assembly: AssemblyVersion("6.0.7")]
[assembly: AssemblyFileVersion("6.0.7")]
[assembly: AssemblyInformationalVersion("6.0.7")]
[assembly: AssemblyCopyright("Apache 2.0 License")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyProduct = "FSharp.Formatting";
        internal const System.String AssemblyDescription = "A package of libraries for building great F# documentation, samples and blogs";
        internal const System.String AssemblyVersion = "6.0.7";
        internal const System.String AssemblyFileVersion = "6.0.7";
        internal const System.String AssemblyInformationalVersion = "6.0.7";
        internal const System.String AssemblyCopyright = "Apache 2.0 License";
    }
}
