// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyProductAttribute("FSharp.Formatting")>]
[<assembly: AssemblyDescriptionAttribute("A package of libraries for building great F# documentation, samples and blogs")>]
[<assembly: AssemblyVersionAttribute("7.2.5")>]
[<assembly: AssemblyFileVersionAttribute("7.2.5")>]
[<assembly: AssemblyInformationalVersionAttribute("7.2.5")>]
[<assembly: AssemblyCopyrightAttribute("Apache 2.0 License")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyProduct = "FSharp.Formatting"
    let [<Literal>] AssemblyDescription = "A package of libraries for building great F# documentation, samples and blogs"
    let [<Literal>] AssemblyVersion = "7.2.5"
    let [<Literal>] AssemblyFileVersion = "7.2.5"
    let [<Literal>] AssemblyInformationalVersion = "7.2.5"
    let [<Literal>] AssemblyCopyright = "Apache 2.0 License"
