// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("FSharp.Formatting")]
[assembly: AssemblyProductAttribute("FSharp.Formatting")]
[assembly: AssemblyDescriptionAttribute("A package of libraries for building great F# documentation, samples and blogs")]
[assembly: AssemblyVersionAttribute("2.13.5")]
[assembly: AssemblyFileVersionAttribute("2.13.5")]
[assembly: AssemblyInformationalVersionAttribute("2.13.5")]
[assembly: AssemblyCopyrightAttribute("Apache 2.0 License")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.13.5";
    }
}
