// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("FSharp.Formatting")]
[assembly: AssemblyProductAttribute("FSharp.Formatting")]
[assembly: AssemblyDescriptionAttribute("A package of libraries for building great F# documentation, samples and blogs")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
[assembly: AssemblyInformationalVersionAttribute("3.0.0-beta01")]
[assembly: AssemblyCopyrightAttribute("Apache 2.0 License")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "FSharp.Formatting";
        internal const System.String AssemblyProduct = "FSharp.Formatting";
        internal const System.String AssemblyDescription = "A package of libraries for building great F# documentation, samples and blogs";
        internal const System.String AssemblyVersion = "3.0.0";
        internal const System.String AssemblyFileVersion = "3.0.0";
        internal const System.String AssemblyInformationalVersion = "3.0.0-beta01";
        internal const System.String AssemblyCopyright = "Apache 2.0 License";
    }
}
